language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
install:
  - pip install coverage
script: nosetests tests --verbose -with-coverage
notifications:
  email:
    - dev.har07@gmail.com
