language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
install:
  - pip install python-coveralls
  - pip install coveralls
script: nosetests tests --verbose --with-coverage
after-success:
  coveralls
notifications:
  email:
    - dev.har07@gmail.com
